### PR TITLE
Fixed a typo in the jquery iterator pattern

### LINKED ISSUE #185: typo in the jquery iterator pattern
Found a typo in the jquery iterator pattern example, with unnecessary extra quote in the log call.
PR coming up..

### PR DESCRIPTION
**Pull request by adnasa**
Fixed #185

### CODE REVIEW

**Comment by addyosmani** [comment]
Can you rebase against master please?

**Comment by adnasa** [comment]
done.

**Comment by morenoh149** [comment]
PR should be closed if fixed elsewhere

**Comment by addyosmani** [comment]
This was indeed fixed in a previous merge commit :tired_face: Sorry about that! I do appreciate the patch and effort to rebase it however. Rock on!

**Pull request closed without merging**
